# Generated by Django 3.1 on 2022-03-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('engaged_in_any_economy', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_activity_engaged_in', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('listen_n_understand_finance_minister', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_your_perception_about_the_elevy', models.CharField(blank=True, max_length=200, null=True)),
                ('should_government_increase_the_threshold', models.CharField(blank=True, max_length=200, null=True)),
                ('should_the_government_reduce_elevy_tax', models.CharField(blank=True, max_length=200, null=True)),
                ('has_there_been_enough_sensitization', models.CharField(blank=True, max_length=200, null=True)),
                ('enough_publicity_about_today_Town_Hall_Meeting', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='preSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('engaged_in_any_economy', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_activity_engaged_in', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('aware_of_elevy_introduction', models.CharField(blank=True, max_length=200, null=True)),
                ('support_elevy_introduction', models.CharField(blank=True, max_length=200, null=True)),
                ('gov_considered_other_area_instead_elevy', models.CharField(blank=True, max_length=200, null=True)),
                ('should_government_increase_tax_or_elevy', models.CharField(blank=True, max_length=200, null=True)),
                ('elevy_affect_momo_business', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_elevy_help_govenment', models.CharField(blank=True, max_length=200, null=True)),
                ('ur_opinion_elevey_increase_revenue', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('engaged_in_any_economy', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_activity_engaged_in', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('aware_of_suspension_of_the_referendum', models.CharField(blank=True, max_length=200, null=True)),
                ('why_do_u_think_is_ryt_direction', models.CharField(blank=True, max_length=200, null=True)),
                ('no_why_do_u_think_is_ryt_direction', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
