# Generated by Django 3.1 on 2022-03-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_questionaire_if_no_why'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaire',
            old_name='why_do_u_think_is_ryt_direction',
            new_name='do_u_think_is_ryt_direction',
        ),
    ]
