# Generated by Django 3.1 on 2022-03-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20220330_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaire',
            old_name='if_no_why',
            new_name='why_not_aware',
        ),
    ]
