# Generated by Django 3.1 on 2022-05-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20220504_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presurvey',
            old_name='collection_elevy_help_government',
            new_name='collection_elevy_help_govenment',
        ),
    ]
