# Generated by Django 3.1 on 2022-05-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20220504_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('dio_name', models.CharField(max_length=200)),
                ('dio_contact', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('engaged_in_any_economy', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_activity_engaged_in', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('aware_of_suspension_of_the_referendum', models.CharField(blank=True, max_length=200, null=True)),
                ('why_not_aware', models.CharField(blank=True, max_length=200, null=True)),
                ('do_u_think_is_ryt_direction', models.CharField(blank=True, max_length=200, null=True)),
                ('no_why_do_u_think_is_ryt_direction', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Questionaire',
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='has_there_been_enough_sensitization',
            new_name='contact_of_respondent',
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='should_government_increase_the_threshold',
            new_name='dio_contact',
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='collection_elevy_help_govenment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='dio_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='do_you_support_government_decision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='give_reason_for_your_opinion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='name_of_respondent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='what_rate_do_you_suggest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='why_not_enough_publicity_about_today_Town_Hall_Meeting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='why_not_listen_finance_minister',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='why_not_support_government_decision',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='why_wont_collection_elevy_help_govenment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
