# Generated by Django 3.1 on 2022-05-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20220505_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('dio_name', models.CharField(max_length=200)),
                ('dio_contact', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('engaged_in_any_economy', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_activity_engaged_in', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('describe_current_situation', models.CharField(blank=True, max_length=200, null=True)),
                ('why_not_describe_current_situation', models.CharField(blank=True, max_length=200, null=True)),
                ('feel_safe_in_country', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_in_security_agencies', models.CharField(blank=True, max_length=500, null=True)),
                ('why_no_confidence_in_security_agencies', models.CharField(blank=True, max_length=500, null=True)),
                ('rate_handling_in_security_agencies', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_of_respondent', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
