# Generated by Django 3.1 on 2022-05-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_questionaire2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire2',
            name='describe_current_situation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='feel_safe_in_country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
