# Generated by Django 3.2.13 on 2022-07-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20220505_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('dio_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dio_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('engaged_in_any_economy', models.CharField(blank=True, max_length=200, null=True)),
                ('economic_activity_engaged_in', models.CharField(blank=True, max_length=200, null=True)),
                ('education_level', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_your_sim_card', models.CharField(blank=True, max_length=200, null=True)),
                ('delay_in_issuance_Ghana_card_affected_Sim_registration', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='collection_elevy_help_govenment',
            new_name='enough_sensitization_elevy',
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='give_reason_for_your_opinion',
            new_name='give_reason_for_your_opinion_increase_the_threshold',
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='what_rate_do_you_suggest',
            new_name='government_should_reduce_rate_allotted_elevy',
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='why_not_support_government_decision',
            new_name='gps_of_structure',
        ),
        migrations.RenameField(
            model_name='postsurvey',
            old_name='do_you_support_government_decision',
            new_name='think_the_Government_should_increase_the_threshold',
        ),
        migrations.RenameField(
            model_name='presurvey',
            old_name='enough_sensitization_campaign_on_elevy',
            new_name='do_you_see_the_elevy_bestway_increase_revenue',
        ),
        migrations.RenameField(
            model_name='presurvey',
            old_name='if_no_enough_sensitization_campaign_on_elevy',
            new_name='gps_of_structure',
        ),
        migrations.RenameField(
            model_name='presurvey',
            old_name='if_yes_enough_sensitization_campaign_on_elevy',
            new_name='reasons_elevy_bestway_increase_revenue',
        ),
        migrations.RenameField(
            model_name='questionaire2',
            old_name='confidence_in_security_agencies',
            new_name='aware_the_easing_restrictions_by_president',
        ),
        migrations.RenameField(
            model_name='questionaire2',
            old_name='contact_of_respondent',
            new_name='have_confidence_in_government_handling_risk_covid19',
        ),
        migrations.RenameField(
            model_name='questionaire2',
            old_name='describe_current_situation',
            new_name='how_would_you_rate_government_handling_covid19',
        ),
        migrations.RenameField(
            model_name='questionaire2',
            old_name='feel_safe_in_country',
            new_name='think_easing_restrictions_by_president_call_right_direction',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='should_the_government_reduce_elevy_tax',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='why_not_enough_publicity_about_today_Town_Hall_Meeting',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='why_not_listen_finance_minister',
        ),
        migrations.RemoveField(
            model_name='postsurvey',
            name='why_wont_collection_elevy_help_govenment',
        ),
        migrations.RemoveField(
            model_name='presurvey',
            name='platform_you_heard_on',
        ),
        migrations.RemoveField(
            model_name='presurvey',
            name='should_government_increase_tax_or_elevy',
        ),
        migrations.RemoveField(
            model_name='presurvey',
            name='why_dont_you_support',
        ),
        migrations.RemoveField(
            model_name='questionaire2',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='questionaire2',
            name='rate_handling_in_security_agencies',
        ),
        migrations.RemoveField(
            model_name='questionaire2',
            name='why_no_confidence_in_security_agencies',
        ),
        migrations.RemoveField(
            model_name='questionaire2',
            name='why_not_describe_current_situation',
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='reason_publicity_about_today_Town_Hall_Meeting',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='postsurvey',
            name='reason_reduce_rate_allotted_elevy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
