# Generated by Django 3.2.13 on 2022-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20220710_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire2',
            name='if_no_why_think_easing_restrictions_by_president_call_right_direction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
