# Generated by Django 3.2.13 on 2022-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_rename_if_no_why_think_easing_restrictions_by_president_call_right_direction_questionaire2_if_no_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsurvey',
            name='changed_your_perception_about_the_elevy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='contact_of_respondent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='dio_contact',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='dio_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='district',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='economic_activity_engaged_in',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='education_level',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='engaged_in_any_economy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='enough_publicity_about_today_Town_Hall_Meeting',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='listen_n_understand_finance_minister',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='name_of_respondent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='region',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='sex',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='think_the_Government_should_increase_the_threshold',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='aware_of_elevy_introduction',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='contact_of_respondent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='dio_contact',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='dio_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='district',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='do_you_see_the_elevy_bestway_increase_revenue',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='economic_activity_engaged_in',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='education_level',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='elevy_affect_momo_business',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='engaged_in_any_economy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='gov_considered_other_area_instead_elevy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='name_of_respondent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='region',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='sex',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='support_elevy_introduction',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='why_wont_collection_elevy_help_govenment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='aware_of_suspension_of_the_referendum',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='dio_contact',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='dio_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='district',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='do_u_think_is_ryt_direction',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='economic_activity_engaged_in',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='education_level',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='engaged_in_any_economy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='no_why_do_u_think_is_ryt_direction',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='region',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='sex',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire1',
            name='why_not_aware',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='contact_of_respondent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='dio_contact',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='dio_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='district',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='economic_activity_engaged_in',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='education_level',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='engaged_in_any_economy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='have_confidence_in_government_handling_risk_covid19',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='if_no_why_have_confidence_in_government_handling_risk_covid19',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='region',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire2',
            name='sex',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='delay_in_issuance_Ghana_card_affected_Sim_registration',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='dio_contact',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='dio_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='district',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='economic_activity_engaged_in',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='education_level',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='engaged_in_any_economy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='region',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='registered_your_sim_card',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionaire4',
            name='sex',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
