# Generated by Django 3.2.13 on 2022-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20220710_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presurvey',
            old_name='support_elevy_introduction',
            new_name='if_no_why_support_Governments_decision_introduce_elevy',
        ),
        migrations.AddField(
            model_name='presurvey',
            name='support_Governments_decision_introduce_elevy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
