# Generated by Django 3.2.13 on 2022-07-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20220710_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsurvey',
            name='reasons_for_changed_your_perception_about_the_elevy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
