# Generated by Django 4.1.2 on 2022-10-26 21:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_welcomemessage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaireInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
