# Generated by Django 4.1.2 on 2022-10-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_questionaireinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaireinfo',
            old_name='message',
            new_name='description',
        ),
    ]
